#!/usr/bin/env python3
# Generated by `artzain init --framework crewai` (artzain __COGNEXUS_PKG_VERSION__).
# Decision API origin when generated: __COGNEXUS_BASE_URL__
"""CrewAI + CogNEXUS — clear the tool before the agent uses it.

The seam
--------
CrewAI agents reach the outside world through tools, so the tool is the seam.
Wrapping the tool (rather than checking after the crew finishes) means a
denied action never happens at all — a post-hoc check would be an audit trail
of damage already done.

    agent ──► guarded tool ──► gate ──┬── allow  ──► real tool runs
                                      ├── review ──► returns "queued"
                                      └── deny   ──► returns the reasons

The agent sees the refusal as a normal tool result and can reason about it,
which is usually what you want: it re-plans instead of crashing.

Install::

    pip install artzain crewai crewai-tools

Run::

    python artzain_crewai_guard.py
"""

from __future__ import annotations

import functools
import json
import os
from typing import Any, Callable

import artzain

try:
    from crewai import Agent, Crew, Task
    from crewai.tools import tool
except ImportError:  # pragma: no cover - scaffold guidance, not library code
    raise SystemExit("This example needs CrewAI:  pip install crewai crewai-tools")


AGENT_DID = os.environ.get("COGNEXUS_AGENT_DID", "crewai-demo-agent")


# ── The guard decorator ──────────────────────────────────────────────────────


def governed(action: str, target: str) -> Callable:
    """Wrap a CrewAI tool so every invocation clears the Decision API first.

    Stack it *under* @tool so CrewAI sees the guarded callable:

        @tool("send_email")
        @governed(action="send_email", target="crm:contact:123")
        def send_email(body: str) -> str: ...
    """

    def decorator(fn: Callable) -> Callable:
        @functools.wraps(fn)
        def wrapper(*args: Any, **kwargs: Any) -> str:
            payload = json.dumps(
                {"tool": fn.__name__, "args": args, "kwargs": kwargs},
                default=str,
            )
            try:
                d = artzain.decide(
                    action=action,
                    target=target,
                    payload=payload,
                    kind="tool_call",
                    agent_did=AGENT_DID,
                    surface="crewai",
                )
            except artzain.DecisionError as exc:
                # HTTP 503 means the engine refused to decide (audit
                # unavailable or kill switch). Fail closed.
                return f"REFUSED: decision unavailable ({exc}) — failing closed."

            outcome = d.get("outcome", "deny")
            decision_id = d.get("decision_id", "")

            if outcome == "deny":
                reasons = "; ".join(d.get("reasons", [])) or "policy denied this action"
                # Returned as a tool result, not raised: the agent can re-plan.
                return f"REFUSED: {reasons} (decision {decision_id})"

            if outcome == "review":
                return (
                    "QUEUED FOR REVIEW: a human must approve this before it "
                    f"runs. Do not retry. (decision {decision_id})"
                )

            result = fn(*args, **kwargs)
            return f"{result} (sealed as {decision_id})"

        return wrapper

    return decorator


# ── A guarded tool ───────────────────────────────────────────────────────────


@tool("send_email")
@governed(action="send_email", target="crm:contact:123")
def send_email(body: str) -> str:
    """Send a follow-up email to the CRM contact."""
    # Replace with the real side effect. It only ever runs on `allow`.
    return f"Sent email ({len(body)} chars)."


def main() -> None:
    if not os.environ.get("COGNEXUS_API_KEY"):
        print("Note: no COGNEXUS_API_KEY set — tool calls run against the local")
        print("guard library and are not sealed. `artzain login` takes ~15s.\n")

    outreach = Agent(
        role="Outreach assistant",
        goal="Send a short, accurate follow-up to the contact.",
        backstory="You draft concise follow-ups and never invent commitments.",
        tools=[send_email],
        verbose=True,
    )

    task = Task(
        description=(
            "Draft and send a two-sentence follow-up to contact 123 about "
            "yesterday's meeting."
        ),
        expected_output="Confirmation that the email was sent, or the refusal reason.",
        agent=outreach,
    )

    result = Crew(agents=[outreach], tasks=[task], verbose=True).kickoff()
    print(f"\nCrew result:\n{result}")


if __name__ == "__main__":
    main()
