#!/usr/bin/env python3
# Generated by `artzain init --framework mcp` (artzain __COGNEXUS_PKG_VERSION__).
# Decision API origin when generated: __COGNEXUS_BASE_URL__
"""MCP server + CogNEXUS — clear the tool call before it executes.

The seam
--------
An MCP server's dangerous moment is inside `call_tool`, after the client has
asked for a tool and before you run it. Gating there covers every client and
every transport, and it is the one place the *arguments* are known.

    client ──► call_tool ──► gate ──┬── allow  ──► run the tool
                                    ├── review ──► return "queued", do nothing
                                    └── deny   ──► return the reasons

Note the payload kind: `tool_call`. That selects the tool-contract and
destructive-action guards, which is what you want for a structured call —
`model_output` would screen it as prose instead.

Install::

    pip install artzain mcp

Run::

    python artzain_mcp_guard.py        # stdio server
"""

from __future__ import annotations

import json
import os
from typing import Any

import artzain

try:
    from mcp.server import Server
    from mcp.server.stdio import stdio_server
    from mcp.types import TextContent, Tool
except ImportError:  # pragma: no cover - scaffold guidance, not library code
    raise SystemExit("This example needs the MCP SDK:  pip install mcp")


AGENT_DID = os.environ.get("COGNEXUS_AGENT_DID", "mcp-demo-server")

app = Server("artzain-guarded-demo")


# ── The tools this server exposes ────────────────────────────────────────────


@app.list_tools()
async def list_tools() -> list[Tool]:
    return [
        Tool(
            name="send_email",
            description="Send an email to a CRM contact.",
            inputSchema={
                "type": "object",
                "properties": {
                    "contact_id": {"type": "string"},
                    "body": {"type": "string"},
                },
                "required": ["contact_id", "body"],
            },
        ),
        Tool(
            name="execute_sql",
            description="Run a read query against the analytics warehouse.",
            inputSchema={
                "type": "object",
                "properties": {"query": {"type": "string"}},
                "required": ["query"],
            },
        ),
    ]


# ── The gate ─────────────────────────────────────────────────────────────────


def gate(tool_name: str, arguments: dict[str, Any]) -> dict[str, Any]:
    """Clear one tool call. Returns the decision, or a synthetic deny.

    The whole argument object is the payload — the guards need to see the
    arguments, not a summary of them.
    """
    target = (
        f"crm:contact:{arguments.get('contact_id')}"
        if tool_name == "send_email"
        else "db:analytics"
    )
    try:
        return artzain.decide(
            action=tool_name,
            target=target,
            payload=json.dumps({"tool": tool_name, "arguments": arguments}),
            kind="tool_call",
            agent_did=AGENT_DID,
            surface="mcp",
        )
    except artzain.DecisionError as exc:
        # HTTP 503 means the engine refused to decide (audit unavailable or
        # kill switch). Fail closed — an ungoverned tool call is the thing
        # this server exists to prevent.
        return {
            "outcome": "deny",
            "reasons": [f"decision unavailable ({exc}) — failing closed"],
            "decision_id": "",
        }


@app.call_tool()
async def call_tool(name: str, arguments: dict[str, Any]) -> list[TextContent]:
    d = gate(name, arguments)
    outcome = d.get("outcome", "deny")
    decision_id = d.get("decision_id", "")

    if outcome == "deny":
        reasons = "; ".join(d.get("reasons", [])) or "policy denied this call"
        return [TextContent(
            type="text",
            text=f"REFUSED: {reasons}\n(decision {decision_id})",
        )]

    if outcome == "review":
        # Do not act yet — a human owns this one now.
        return [TextContent(
            type="text",
            text=(
                "QUEUED FOR REVIEW: this call needs human approval before it "
                f"runs.\n(decision {decision_id})"
            ),
        )]

    # allow — and only now does the tool actually execute.
    result = run_tool(name, arguments)
    return [TextContent(type="text", text=f"{result}\n(sealed as {decision_id})")]


def run_tool(name: str, arguments: dict[str, Any]) -> str:
    """Stand-in for the real side effect. Replace with your implementation."""
    if name == "send_email":
        return f"Sent email to contact {arguments.get('contact_id')}."
    if name == "execute_sql":
        return f"Ran query: {arguments.get('query')}"
    return f"Unknown tool {name!r}."


async def main() -> None:
    if not os.environ.get("COGNEXUS_API_KEY"):
        print(
            "Note: no COGNEXUS_API_KEY set — calls run against the local guard "
            "library and are not sealed. `artzain login` takes ~15s.",
            flush=True,
        )
    async with stdio_server() as (read, write):
        await app.run(read, write, app.create_initialization_options())


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
