#!/usr/bin/env python3
# Generated by `artzain init --framework mcp` (artzain __COGNEXUS_PKG_VERSION__).
# Decision API origin when generated: __COGNEXUS_BASE_URL__
"""MCP server + CogNEXUS — clear the tool call before it executes.

The seam
--------
An MCP server's dangerous moment is inside `call_tool`, after the client has
asked for a tool and before you run it. Gating there covers every client and
every transport, and it is the one place the *arguments* are known.

    client ──► call_tool ──► gate ──┬── allow  ──► run the tool
                                    ├── review ──► return "queued", do nothing
                                    └── deny   ──► return the reasons

Only `allow` runs the tool, and `review` queues it. `deny`, or any outcome this
code does not know (missing, misspelt, or added in a later release), refuses
it. A call that did not run comes back as a failed tool call (`is_error`), so
a model or client never takes the refusal or the queued notice for the tool's
output. So does a call to a tool this server does not list, refused without a
decision, and a call that raises: its error goes to the server's log
(stderr), not into the reply. `decide()` blocks on the network, so the gate
runs in a worker thread and the server keeps answering other requests while
it waits.

Note the payload kind: `tool_call`. That selects the tool-contract and
destructive-action guards, which is what you want for a structured call —
`model_output` would skip the tool-contract check.

This file uses the MCP SDK 2.x low-level server. `call_tool` is the one
handler every tool call reaches, passed to the `Server` constructor as
`on_call_tool`. On the 1.x SDK, which registers handlers with decorators, the
file exits saying what to install.

Install::

    pip install artzain "mcp>=2,<3"

Run::

    python artzain_mcp_guard.py        # stdio server
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
from typing import Any

import artzain

try:
    from mcp.server import Server, ServerRequestContext
    from mcp.server.stdio import stdio_server
    from mcp.types import (
        CallToolRequestParams,
        CallToolResult,
        ListToolsResult,
        PaginatedRequestParams,
        TextContent,
        Tool,
    )
except ImportError:  # pragma: no cover - scaffold guidance, not library code
    # No MCP SDK, or the 1.x SDK, whose `mcp.server` has no ServerRequestContext.
    raise SystemExit('This example needs the MCP SDK 2.x:  pip install "mcp>=2,<3"')


AGENT_DID = os.environ.get("COGNEXUS_AGENT_DID", "mcp-demo-server")

log = logging.getLogger("artzain_mcp_guard")


# ── The tools this server exposes ────────────────────────────────────────────

TOOLS = [
    Tool(
        name="send_email",
        description="Send an email to a CRM contact.",
        input_schema={
            "type": "object",
            "properties": {
                "contact_id": {"type": "string"},
                "body": {"type": "string"},
            },
            "required": ["contact_id", "body"],
        },
    ),
    Tool(
        name="execute_sql",
        description="Run a read query against the analytics warehouse.",
        input_schema={
            "type": "object",
            "properties": {"query": {"type": "string"}},
            "required": ["query"],
        },
    ),
]


async def list_tools(
    ctx: ServerRequestContext, params: PaginatedRequestParams | None
) -> ListToolsResult:
    return ListToolsResult(tools=TOOLS)


# ── The gate ─────────────────────────────────────────────────────────────────


def gate(tool_name: str, arguments: dict[str, Any]) -> dict[str, Any]:
    """Clear one tool call. Returns the decision, or a synthetic deny.

    The whole argument object is the payload — the guards need to see the
    arguments, not a summary of them.
    """
    target = (
        f"crm:contact:{arguments.get('contact_id')}"
        if tool_name == "send_email"
        else "db:analytics"
    )
    try:
        return artzain.decide(
            action=tool_name,
            target=target,
            # Keep ensure_ascii=False: the default writes non-Latin text as
            # \uXXXX escapes, and the injection screen denies a run of them as
            # an encoding attack.
            payload=json.dumps(
                {"tool": tool_name, "arguments": arguments},
                ensure_ascii=False,
            ),
            kind="tool_call",
            agent_did=AGENT_DID,
            surface="mcp",
        )
    except artzain.DecisionError as exc:
        # HTTP 503 means the engine refused to decide (audit unavailable or
        # kill switch). Fail closed — an ungoverned tool call is the thing
        # this server exists to prevent.
        return {
            "outcome": "deny",
            "reasons": [f"decision unavailable ({exc}) — failing closed"],
            "decision_id": "",
        }


async def call_tool(ctx: ServerRequestContext, params: CallToolRequestParams) -> CallToolResult:
    name = params.name
    # A client may leave the arguments out; the 1.x server passed {} for them.
    arguments = params.arguments or {}
    if name not in {tool.name for tool in TOOLS}:
        # Nothing this server could run, so nothing to decide.
        return reply(f"Unknown tool {name!r}.", is_error=True)
    try:
        return await gated_call(name, arguments)
    except Exception:
        # Left to the 2.x server, the exception's text would reach the client
        # (over the 2025 protocol, as the error's message), and it can quote
        # a password or a key. The traceback goes to the log (stderr); the
        # reply says only that the call failed.
        log.exception("Tool call %r failed", name)
        return reply(
            f"FAILED: the call to {name!r} raised an error; see the server log.",
            is_error=True,
        )


async def gated_call(name: str, arguments: dict[str, Any]) -> CallToolResult:
    # decide() blocks on the network: run the gate in a worker thread so the
    # event loop keeps serving other requests while it waits.
    d = await asyncio.to_thread(gate, name, arguments)
    outcome = d.get("outcome")
    decision_id = d.get("decision_id", "")

    if outcome == "allow":
        # Only now does the tool actually execute.
        result = run_tool(name, arguments)
        return reply(f"{result}\n(sealed as {decision_id})")

    if outcome == "review":
        # Do not act yet — a human owns this one now.
        return reply(
            "QUEUED FOR REVIEW: this call needs human approval before it "
            f"runs.\n(decision {decision_id})",
            is_error=True,
        )

    # deny, and any outcome this code does not know: never run the tool on it.
    if outcome == "deny":
        reasons = "; ".join(d.get("reasons") or []) or "policy denied this call"
    else:
        reasons = f"unrecognised outcome {outcome!r} — failing closed"
    return reply(f"REFUSED: {reasons}\n(decision {decision_id})", is_error=True)


def reply(text: str, *, is_error: bool = False) -> CallToolResult:
    """The whole result: the 2.x server sends what a handler returns as it is."""
    return CallToolResult(content=[TextContent(type="text", text=text)], is_error=is_error)


def run_tool(name: str, arguments: dict[str, Any]) -> str:
    """Stand-in for the real side effect. Replace with your implementation.

    The 2.x server does not check the arguments against the tool's
    `input_schema` (the 1.x server did), so check them here before acting.
    """
    if name == "send_email":
        return f"Sent email to contact {arguments.get('contact_id')}."
    if name == "execute_sql":
        return f"Ran query: {arguments.get('query')}"
    raise NotImplementedError(f"TOOLS lists {name!r}, but run_tool has no code for it")


# ── The server ───────────────────────────────────────────────────────────────

app = Server("artzain-guarded-demo", on_list_tools=list_tools, on_call_tool=call_tool)


async def main() -> None:
    if not os.environ.get("COGNEXUS_API_KEY"):
        # stderr: stdout carries the JSON-RPC stream a stdio client reads.
        print(
            "Note: no COGNEXUS_API_KEY set — calls run against the local guard "
            "library and are not sealed. `artzain login` takes ~15s.",
            file=sys.stderr,
            flush=True,
        )
    async with stdio_server() as (read, write):
        await app.run(read, write, app.create_initialization_options())


if __name__ == "__main__":
    asyncio.run(main())
