// Generated by `artzain init --framework openclaw` (artzain __COGNEXUS_PKG_VERSION__).
// Decision API origin when generated: __COGNEXUS_BASE_URL__
/**
 * OpenClaw + CogNEXUS — clear the tool call before it executes.
 *
 * This is a worked example, not a ClawHub plugin. Copy the file into an
 * OpenClaw plugin package you already load from `openclaw.json`. Do not
 * publish it as `@cognexuslabs/…` on ClawHub from this scaffold.
 *
 * The seam
 * --------
 * Envelope (pattern B) screens the *model* round-trip. It never sees host
 * tools (`exec`, `apply_patch`, `browser`, `message`, …). The dangerous
 * moment is `before_tool_call`, after the model asked for a tool and before
 * OpenClaw runs it. Gating there is the same idea as the MCP `call_tool`
 * scaffold.
 *
 *     model ──► before_tool_call ──► gate ──┬── allow  ──► run the tool
 *                                           ├── review ──► { block: true }
 *                                           └── deny   ──► { block: true }
 *
 * `review` is **not** OpenClaw `/approve`. CogNEXUS review lives in the
 * dashboard Review Queue (session auth). Mapping it onto Gateway approval
 * would pretend the human clicked inside OpenClaw. Block instead.
 *
 * Note the payload kind: `tool_call`. That selects the tool-contract and
 * destructive-action guards — `model_output` would screen the call as prose.
 *
 * Install (inside the plugin package)::
 *
 *     npm install @cognexuslabs/artzain
 *
 * Set `COGNEXUS_API_KEY` on the Gateway process (and optionally
 * `COGNEXUS_API_BASE_URL`). The TypeScript SDK is remote-only: a missing
 * key throws `DecisionError` instead of screening offline.
 */

import { definePluginEntry } from "openclaw/plugin-sdk/plugin-entry";
import { configure, decide, DecisionError } from "@cognexuslabs/artzain";

configure({
  baseUrl: process.env.COGNEXUS_API_BASE_URL || "__COGNEXUS_BASE_URL__",
});

const AGENT_DID = process.env.COGNEXUS_AGENT_DID || "openclaw-gateway";

// Policy hooks default to 15s. Decision API latency is tens of milliseconds;
// stay under the budget so a hung call fails closed (OpenClaw rejects the
// tool) rather than racing the timeout.
const HOOK_TIMEOUT_MS = 14_000;
const DECIDE_TIMEOUT_MS = 12_000;

type ToolCallEvent = {
  toolName: string;
  params?: Record<string, unknown>;
  toolCallId?: string;
  runId?: string;
};

type ToolCallCtx = {
  agentId?: string;
  abortSignal?: AbortSignal;
};

function payloadFor(toolName: string, params: unknown): string {
  try {
    return JSON.stringify({ tool: toolName, arguments: params ?? {} });
  } catch {
    return JSON.stringify({ tool: toolName, arguments: { _unserializable: true } });
  }
}

function block(reason: string): { block: true; blockReason: string } {
  return { block: true, blockReason: reason };
}

export default definePluginEntry({
  id: "artzain-tool-gate",
  name: "CogNEXUS tool gate",
  register(api) {
    api.on(
      "before_tool_call",
      async (event: ToolCallEvent, ctx: ToolCallCtx) => {
        const toolName = event.toolName || "unknown_tool";
        const requestId = (event.toolCallId || event.runId || "").slice(0, 64);
        try {
          const decision = await decide({
            action: toolName,
            target: `openclaw:tool:${toolName}`,
            payload: payloadFor(toolName, event.params),
            kind: "tool_call",
            agentDid: ctx.agentId || AGENT_DID,
            surface: "openclaw",
            requestId: requestId || undefined,
            timeoutMs: DECIDE_TIMEOUT_MS,
          });

          if (decision.outcome === "allow") {
            return;
          }

          const reasons = (decision.reasons || []).join("; ") || decision.outcome;
          if (decision.outcome === "review") {
            // Do not act yet — a human owns this in the CogNEXUS Review Queue.
            // Do not map this onto OpenClaw /approve.
            return block(
              `QUEUED FOR REVIEW: ${reasons} (decision ${decision.decision_id})`,
            );
          }

          if (decision.outcome === "deny") {
            return block(`REFUSED: ${reasons} (decision ${decision.decision_id})`);
          }

          return block(`REFUSED: ${reasons} (decision ${decision.decision_id})`);
        } catch (err) {
          // HTTP 503 / missing key / transport failure: the engine refused to
          // decide. Fail closed — an ungoverned tool call is the thing this
          // hook exists to prevent.
          const detail =
            err instanceof DecisionError
              ? err.message
              : err instanceof Error
                ? err.message
                : String(err);
          return block(`decision unavailable (${detail}) — failing closed`);
        }
      },
      { timeoutMs: HOOK_TIMEOUT_MS },
    );
  },
});
