# Generated by `artzain init --framework openshell` (artzain __COGNEXUS_PKG_VERSION__).
# Decision API origin when generated: __COGNEXUS_BASE_URL__
#
# Starting OpenShell policy for an OpenClaw workload (NemoClaw) plus the
# openclaw-artzain plugin. The OpenShell provider holds the Decision API key
# and injects it only toward the ArtzAIn host. The agent process never sees
# the key.
#
# Stacking
# --------
# Pattern B (envelope base_url) screens prompts. It does not see the packet.
# Pattern C (before_tool_call) gates the tool. OpenShell is what remains when
# the plugin is bypassed or the agent runs a shell. OpenShell does not
# understand EU overlays. ArtzAIn does not stop a binary this YAML allows.
#
# Skill
# -----
# Propose the narrowest policy.local rule and wait for a sealed decision.
# Do not approve your own rule. Policy-advisor auto-approve stays off.
# The interceptor calls artzain.decide( before the gateway commits.
# allow proceeds. deny does not. review does not change the sandbox.
# A DecisionError must fail closed: the policy does not change.
# Install the CLI with: pip install artzain
# Regenerate with: artzain init --framework openshell
#
# enforcement is enforce on purpose: omitting it is audit (log-and-allow).
# tls is omitted so the gateway auto-detects. Do not set tls: skip.
version: 1
network_policies:
  artzain:
    binaries:
      - path: "/usr/bin/curl"
    endpoints:
      - host: "artzain.local"
        port: 443
        protocol: rest
        enforcement: enforce
        rules:
          - allow:
              method: "POST"
              path: "/api/v1/decisions"
  inference:
    binaries:
      - path: "/usr/bin/curl"
    endpoints:
      - host: "inference.local"
        port: 443
        protocol: rest
        enforcement: enforce
