"""``artzain local`` — the self-serve in-boundary installer (WS-B).

One command stands the engine up beside a local dashboard:

* ``up``       render the workspace, pull digest-pinned images, wait healthy,
               hand off to the browser's first-run page.
* ``doctor``   preflight; every failure prints one remedial sentence.
* ``status``   health, trial standing, and whether an update is available.
* ``upgrade``  dump the database FIRST, then re-pin to the channel's digests.
* ``down``     stop (data stays); ``--purge`` destroys volumes after an
               explicit confirmation naming the install.
* ``reset``    the dirty-reinstall path: the same confirmation, then purge.
* ``create-admin``  headless first-run (the /welcome page without a browser).

The workspace is ``~/.cognexus`` (override: ``COGNEXUS_LOCAL_HOME``):
``compose.yaml`` is rewritten on every pin change and never hand-edited;
``.env`` is generated with real random secrets and repaired in place if keys
are missing — existing values are never overwritten; ``pins.json`` records
which release is applied (and the install id, so ``--purge`` can name it
even with the stack stopped); ``backups/`` holds the pre-upgrade dumps.

Digests, not tags: the stable-channel manifest (WS-A) names an image digest
per repository — the same digest the release's cosign signature covers — and
the rendered compose file bakes those digests in. The postgres base image is
digest-pinned in the template for the same reason. Nothing here pulls a
bare tag.
"""

from __future__ import annotations

import gzip
import json
import os
import re
import secrets as _secrets
import shutil
import socket
import subprocess
import sys
import urllib.error
import urllib.request
from contextlib import contextmanager
from datetime import datetime, timezone
from importlib import resources
from pathlib import Path
from typing import Any, Callable

__all__ = [
    "DEFAULT_MANIFEST_URL",
    "LocalError",
    "doctor_checks",
    "ensure_workspace",
    "image_refs",
    "load_manifest",
    "render_compose",
    "workspace_dir",
]

DEFAULT_MANIFEST_URL = "https://cognexuslabs.ai/downloads/stable.json"
_COMPOSE_TEMPLATE = "_local_compose.yaml.tpl"
_PROJECT = "cognexus"
_UI_PORT_DEFAULT = 8080
_HEALTH_TIMEOUT_S = 240
_MIN_DUMP_BYTES = 1024  # matches the compose backup floor in the engine repo
_MIN_FREE_BYTES = 2 * 1024**3

_REQUIRED_IMAGES = ("cognexus-core", "cognexus-frontend")
_DIGEST_RE = re.compile(r"^sha256:[0-9a-f]{64}$")

#: Secrets the workspace .env must carry. Generation is per-key so a
#: hand-created file (e.g. someone editing the port before first run) is
#: repaired in place rather than silently left without a Postgres password —
#: the all-or-nothing version of this bricked exactly that path.
_ENV_SECRET_KEYS = (
    ("POSTGRES_PASSWORD", 24),
    ("JWT_SECRET_KEY", 48),
    ("COGNEXUS_API_KEY_PEPPER", 32),
    ("COGNEXUS_BOOTSTRAP_TOKEN", 24),
)

_ENV_HEADER = (
    "# Generated by `artzain local up`. Secrets are per-install; keep the\n"
    "# file. Deleting it (or `artzain local reset`) strands the install's\n"
    "# JWTs and API-key hashes.\n"
)


class LocalError(RuntimeError):
    """A failure with its remedy in the message — print, don't traceback."""


# ---------------------------------------------------------------------------
# Workspace
# ---------------------------------------------------------------------------


def workspace_dir() -> Path:
    override = (os.environ.get("COGNEXUS_LOCAL_HOME") or "").strip()
    return Path(override) if override else Path.home() / ".cognexus"


def _compose_path() -> Path:
    return workspace_dir() / "compose.yaml"


def _env_path() -> Path:
    return workspace_dir() / ".env"


def _pins_path() -> Path:
    return workspace_dir() / "pins.json"


def backups_dir() -> Path:
    return workspace_dir() / "backups"


def _write_atomic(path: Path, text: str) -> None:
    """Never hand a half-written file to a concurrent reader (compose runs
    ``-f`` on these)."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    os.replace(tmp, path)


@contextmanager
def _workspace_lock():
    """One mutating ``artzain local`` command at a time.

    Two concurrent ``up``s each generating secrets can initialise the
    Postgres volume with one password while ``.env`` keeps the other — an
    install nothing short of ``--purge`` recovers. O_EXCL is the portable
    atomic primitive; the lock file names its holder for the stale case.
    """
    workspace_dir().mkdir(parents=True, exist_ok=True)
    lock = workspace_dir() / ".lock"
    try:
        fd = os.open(str(lock), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
    except FileExistsError:
        raise LocalError(
            f"Another `artzain local` command appears to be running (lock: "
            f"{lock}). If that is wrong — e.g. a previous run was killed — "
            "delete the lock file and retry.") from None
    try:
        os.write(fd, f"pid={os.getpid()}\n".encode())
        os.close(fd)
        yield
    finally:
        try:
            lock.unlink()
        except OSError:
            pass


# ---------------------------------------------------------------------------
# Channel manifest
# ---------------------------------------------------------------------------


def manifest_source(explicit: str | None = None) -> str:
    """Precedence: --manifest flag, COGNEXUS_CHANNEL_MANIFEST, the default."""
    return (
        (explicit or "").strip()
        or (os.environ.get("COGNEXUS_CHANNEL_MANIFEST") or "").strip()
        or DEFAULT_MANIFEST_URL
    )


def load_manifest(source: str) -> dict[str, Any]:
    """Fetch and validate a stable-channel manifest (URL or local file)."""
    if source.startswith(("http://", "https://")):
        req = urllib.request.Request(
            source, headers={"Accept": "application/json",
                             "User-Agent": "artzain-local"})
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                raw = resp.read().decode("utf-8")
        except (urllib.error.URLError, OSError) as exc:
            raise LocalError(
                f"Could not fetch the channel manifest from {source} ({exc}). "
                "Pass --manifest <url-or-file> (e.g. the stable.json artifact "
                "from the release run) or set COGNEXUS_CHANNEL_MANIFEST."
            ) from exc
    else:
        path = Path(source)
        if not path.is_file():
            raise LocalError(
                f"Manifest file not found: {path}. Pass --manifest with the "
                "path to a stable.json.")
        raw = path.read_text(encoding="utf-8")

    try:
        manifest = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise LocalError(
            f"The manifest at {source} is not valid JSON — expected the "
            "stable.json the release workflow publishes.") from exc
    return validate_manifest(manifest, source)


def validate_manifest(manifest: Any, source: str = "<manifest>") -> dict[str, Any]:
    if not isinstance(manifest, dict):
        raise LocalError(f"The manifest at {source} is not a JSON object.")
    registry = str(manifest.get("registry") or "").strip().rstrip("/")
    version = str(manifest.get("version") or "").strip()
    images = manifest.get("images")
    if not registry or not version or not isinstance(images, dict):
        raise LocalError(
            f"The manifest at {source} is missing registry/version/images — "
            "it does not look like a stable-channel manifest.")
    for name in _REQUIRED_IMAGES:
        entry = images.get(name)
        digest = str((entry or {}).get("digest") or "")
        if not _DIGEST_RE.match(digest):
            raise LocalError(
                f"The manifest at {source} has no sha256 digest for {name} — "
                "refusing to install from an unpinned manifest.")
    return manifest


def image_refs(manifest: dict[str, Any]) -> dict[str, str]:
    """``repo -> registry/repo@sha256:...`` — digests only, never tags."""
    registry = str(manifest["registry"]).rstrip("/")
    return {
        name: f"{registry}/{name}@{manifest['images'][name]['digest']}"
        for name in _REQUIRED_IMAGES
    }


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def render_compose(manifest: dict[str, Any]) -> str:
    refs = image_refs(manifest)
    template = resources.files("artzain").joinpath(_COMPOSE_TEMPLATE).read_text(
        encoding="utf-8")
    return (template
            .replace("__CORE_IMAGE__", refs["cognexus-core"])
            .replace("__FRONTEND_IMAGE__", refs["cognexus-frontend"]))


def _render_env(existing: dict[str, str],
                ui_port_choice: int | None) -> tuple[str, bool]:
    """The .env content: keep existing values, generate only the missing.

    Returns ``(text, changed)``. ``ui_port_choice`` overrides the stored
    port when explicitly given (the ``--port`` flag); otherwise the stored
    value — or the default — stands.
    """
    values = dict(existing)
    changed = False
    for key, entropy in _ENV_SECRET_KEYS:
        if not values.get(key):
            values[key] = _secrets.token_urlsafe(entropy)
            changed = True
    if ui_port_choice is not None:
        if values.get("COGNEXUS_UI_PORT") != str(ui_port_choice):
            changed = True
        values["COGNEXUS_UI_PORT"] = str(ui_port_choice)
    elif not values.get("COGNEXUS_UI_PORT"):
        values["COGNEXUS_UI_PORT"] = str(_UI_PORT_DEFAULT)
        changed = True
    managed = [k for k, _ in _ENV_SECRET_KEYS] + ["COGNEXUS_UI_PORT"]
    lines = [f"{key}={values[key]}" for key in managed]
    # Preserve any extra keys the operator added (they own this file too).
    extras = [f"{k}={v}" for k, v in values.items() if k not in managed]
    return _ENV_HEADER + "\n".join(lines + extras) + "\n", changed


def read_env() -> dict[str, str]:
    env_file = _env_path()
    values: dict[str, str] = {}
    if not env_file.is_file():
        return values
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        val = val.strip()
        # Hand-edited files often quote values dotenv-style; compose strips
        # quotes, so this parser must too or the two disagree about the port.
        if len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'":
            val = val[1:-1]
        values[key.strip()] = val
    return values


def ui_port() -> int:
    try:
        return int(read_env().get("COGNEXUS_UI_PORT") or _UI_PORT_DEFAULT)
    except ValueError:
        return _UI_PORT_DEFAULT


def base_url() -> str:
    return f"http://localhost:{ui_port()}"


def ensure_workspace(manifest: dict[str, Any],
                     ui_port_choice: int | None = None) -> dict[str, Any]:
    """Write compose.yaml + pins.json; create or REPAIR the .env.

    Existing secret values are never overwritten; missing ones are filled
    in, so a hand-created .env (or one from an interrupted run) cannot
    leave the stack without a Postgres password.
    """
    ws = workspace_dir()
    ws.mkdir(parents=True, exist_ok=True)
    backups_dir().mkdir(parents=True, exist_ok=True)

    existing = read_env()
    env_text, env_changed = _render_env(existing, ui_port_choice)
    if env_changed or not _env_path().is_file():
        _write_atomic(_env_path(), env_text)
        try:  # POSIX only; harmless elsewhere
            _env_path().chmod(0o600)
        except OSError:
            pass

    _write_atomic(_compose_path(), render_compose(manifest))
    pins = applied_pins() or {}
    pins.update({
        "version": manifest.get("version"),
        "registry": manifest.get("registry"),
        "images": manifest.get("images"),
        "source_commit": manifest.get("source_commit"),
        "applied_at": datetime.now(timezone.utc).isoformat(),
    })
    _write_atomic(_pins_path(), json.dumps(pins, indent=2, sort_keys=True))
    return {"workspace": str(ws), "env_created": not existing,
            "env_repaired": bool(existing) and env_changed,
            "version": pins["version"]}


def applied_pins() -> dict[str, Any] | None:
    try:
        return json.loads(_pins_path().read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None


def _remember_install_id(payload: dict[str, Any]) -> None:
    """Persist the install id so ``--purge`` can demand it even when the
    stack is stopped — the normal state in which purges happen."""
    install_id = str(payload.get("install_id") or "").strip()
    pins = applied_pins()
    if not install_id or not pins or pins.get("install_id") == install_id:
        return
    pins["install_id"] = install_id
    _write_atomic(_pins_path(), json.dumps(pins, indent=2, sort_keys=True))


# ---------------------------------------------------------------------------
# Doctor
# ---------------------------------------------------------------------------


def _run(cmd: list[str], timeout: int = 30) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)


def _port_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        # No SO_REUSEADDR: on Windows it lets the bind SUCCEED against a
        # port that is actively in use, making this check pass exactly when
        # it should fail. SO_EXCLUSIVEADDRUSE (Windows-only) asks for the
        # strict semantics explicitly.
        if hasattr(socket, "SO_EXCLUSIVEADDRUSE"):
            s.setsockopt(socket.SOL_SOCKET, socket.SO_EXCLUSIVEADDRUSE, 1)
        try:
            s.bind(("127.0.0.1", port))
            return True
        except OSError:
            return False


def _arch() -> str:
    import platform

    machine = platform.machine().lower()
    if machine in ("x86_64", "amd64"):
        return "amd64"
    if machine in ("arm64", "aarch64"):
        return "arm64"
    return machine


def doctor_checks(port: int | None = None) -> list[tuple[str, bool, str]]:
    """``(name, ok, remedy)`` triples; remedy is one actionable sentence."""
    checks: list[tuple[str, bool, str]] = []
    port = port or ui_port()

    docker = shutil.which("docker") is not None
    checks.append((
        "docker installed", docker,
        "Install Docker Desktop (or Docker Engine + the compose plugin) from "
        "docs.docker.com/get-docker and re-run.",
    ))

    if docker:
        try:
            daemon = _run(["docker", "info", "--format", "{{.ServerVersion}}"]).returncode == 0
        except (OSError, subprocess.TimeoutExpired):
            daemon = False
        checks.append((
            "docker daemon running", daemon,
            "Start Docker Desktop (or `systemctl start docker`) and wait for "
            "it to report running.",
        ))
        try:
            compose_v2 = _run(["docker", "compose", "version"]).returncode == 0
        except (OSError, subprocess.TimeoutExpired):
            compose_v2 = False
        checks.append((
            "docker compose v2", compose_v2,
            "Update Docker Desktop, or install the compose plugin "
            "(docs.docker.com/compose/install).",
        ))

    arch = _arch()
    checks.append((
        f"cpu architecture ({arch})", arch in ("amd64", "arm64"),
        "Published images cover amd64 and arm64 only — run on an x86-64 or "
        "ARM64 host.",
    ))

    running = _stack_running()
    port_ok = _port_free(port) or running
    checks.append((
        f"port {port} available", port_ok,
        f"Something else is listening on {port} — stop it, or re-run with "
        f"`artzain local up --port <port>` (stored in {_env_path()}).",
    ))

    try:
        free = shutil.disk_usage(str(workspace_dir().parent)).free
    except OSError:
        free = _MIN_FREE_BYTES
    checks.append((
        "free disk (>= 2 GB)", free >= _MIN_FREE_BYTES,
        "Free some disk space — the images and database need about 2 GB.",
    ))
    return checks


def _stack_running() -> bool:
    if not _compose_path().is_file():
        return False
    try:
        out = _compose(["ps", "--quiet"], check=False)
        return bool(out.stdout.strip())
    except LocalError:
        return False


# ---------------------------------------------------------------------------
# Compose + HTTP plumbing
# ---------------------------------------------------------------------------


def _compose_cmd(args: list[str]) -> list[str]:
    return ["docker", "compose", "-f", str(_compose_path()),
            "--env-file", str(_env_path()), "-p", _PROJECT, *args]


def _compose(args: list[str], check: bool = True,
             timeout: int = 900) -> subprocess.CompletedProcess:
    try:
        proc = subprocess.run(_compose_cmd(args), capture_output=True,
                              text=True, timeout=timeout)
    except FileNotFoundError as exc:
        raise LocalError("docker is not installed — run `artzain local "
                         "doctor` for the fix.") from exc
    except subprocess.TimeoutExpired as exc:
        raise LocalError(f"`docker compose {args[0]}` timed out after "
                         f"{timeout}s.") from exc
    if check and proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "").strip().splitlines()[-8:]
        raise LocalError(
            f"`docker compose {' '.join(args)}` failed:\n  " + "\n  ".join(tail))
    return proc


def _get_json(path: str, timeout: float = 5.0) -> dict[str, Any] | None:
    """GET a local engine endpoint; ``None`` means unreachable/not JSON —
    an answer, not an error, on a stack that may simply not be up yet."""
    try:
        with urllib.request.urlopen(f"{base_url()}{path}",
                                    timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except Exception:  # noqa: BLE001
        return None


def fetch_health(timeout: float = 5.0) -> dict[str, Any] | None:
    return _get_json("/health", timeout=timeout)


def wait_healthy(timeout_s: int = _HEALTH_TIMEOUT_S,
                 sleep: Callable[[float], None] | None = None,
                 log: Callable[[str], None] = lambda s: None) -> dict[str, Any]:
    import time

    sleep = sleep or time.sleep
    deadline = time.monotonic() + timeout_s
    last = "the engine to answer /health"
    while time.monotonic() < deadline:
        payload = fetch_health()
        if payload:
            status = payload.get("status")
            if status == "healthy":
                return payload
            last = f"status={status} (db={payload.get('db_connected')})"
        log(f"waiting on {last} ...")
        sleep(3)
    raise LocalError(
        f"The engine did not report healthy within {timeout_s}s (last: "
        f"{last}). `docker compose -p {_PROJECT} logs analyzer` shows why.")


def _api_post(path: str, body: dict[str, Any],
              timeout: float = 30.0) -> tuple[int, dict[str, Any]]:
    data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(
        f"{base_url()}{path}", data=data,
        headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.status, json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        raw = exc.read().decode("utf-8", errors="replace")
        try:
            return exc.code, json.loads(raw)
        except json.JSONDecodeError:
            # A gateway's HTML error page is still the only diagnostic the
            # caller has — keep it, don't flatten it to {}.
            return exc.code, {"detail": raw[:300]}
    except (urllib.error.URLError, OSError) as exc:
        raise LocalError(f"Could not reach the engine at {base_url()}: "
                         f"{exc}") from exc


def login_session(email: str, password: str) -> str:
    """Email/password login against the LOCAL engine; returns the JWT.

    The activate flow's fallback for operators who never minted an API key
    — which, on an expired trial, they can no longer do.
    """
    status, payload = _api_post("/api/auth/login",
                                {"email": email, "password": password})
    if status == 200 and payload.get("mfa_required"):
        raise LocalError(
            "This account has two-factor enabled, which the CLI login cannot "
            "complete. Sign in on the dashboard and create an API key there "
            "(Account -> API keys), then set COGNEXUS_API_KEY and retry.")
    token = payload.get("token") if status == 200 else None
    if not token:
        detail = payload.get("detail")
        raise LocalError(f"Sign-in failed (HTTP {status}): "
                         f"{detail or 'invalid email or password'}")
    return str(token)


def bootstrap_state(retries: int = 3,
                    sleep: Callable[[float], None] | None = None) -> dict[str, Any]:
    """The /welcome pre-check, with the *reason* preserved.

    ``unreachable`` (transient) must never be mistaken for
    ``already_bootstrapped`` — that mistake sent fresh installs to a login
    page with zero accounts.
    """
    import time

    sleep = sleep or time.sleep
    for attempt in range(retries):
        state = _get_json("/api/auth/bootstrap-status", timeout=10)
        if isinstance(state, dict) and "available" in state:
            return state
        if attempt < retries - 1:
            sleep(2)
    return {"available": False, "reason": "unreachable"}


def first_run_plan() -> tuple[str, str]:
    """``(url, note)`` for the end of ``up`` — a pure decision, testable.

    * available            -> the one-time /welcome URL.
    * already_bootstrapped -> /login.
    * disabled             -> /login, with a note (no token configured).
    * unreachable/unavailable -> STILL the /welcome URL (the page guards
      itself), plus an honest note and the headless fallback.
    """
    token = read_env().get("COGNEXUS_BOOTSTRAP_TOKEN") or ""
    state = bootstrap_state()
    reason = state.get("reason")
    welcome = f"{base_url()}/welcome?token={token}" if token else ""
    if state.get("available") and welcome:
        return welcome, "The account you create there is the platform admin."
    if reason == "already_bootstrapped" or not welcome:
        return f"{base_url()}/login", "This install already has an account."
    if reason == "disabled":
        return (f"{base_url()}/login",
                "Bootstrap is disabled on this deployment (no token "
                "configured server-side).")
    return (welcome,
            "The first-run status probe did not answer; if that page says "
            "the install is already set up, sign in at /login instead — or "
            "run `artzain local create-admin --email you@example.com`.")


# ---------------------------------------------------------------------------
# Commands (printing lives here; cli.py stays a thin veneer)
# ---------------------------------------------------------------------------


def run_doctor(port: int | None = None, out=None) -> bool:
    out = out or sys.stdout
    ok_all = True
    for name, ok, remedy in doctor_checks(port):
        mark = "ok " if ok else "FAIL"
        print(f"  [{mark}] {name}", file=out)
        if not ok:
            print(f"        -> {remedy}", file=out)
            ok_all = False
    return ok_all


def run_up(manifest_src: str | None, open_browser: bool = True,
           port: int | None = None, out=None) -> None:
    out = out or sys.stdout
    with _workspace_lock():
        print("Preflight:", file=out)
        if not run_doctor(port=port, out=out):
            raise LocalError("Fix the checks above and re-run "
                             "`artzain local up`.")

        source = manifest_source(manifest_src)
        print(f"Channel manifest: {source}", file=out)
        manifest = load_manifest(source)
        state = ensure_workspace(manifest, ui_port_choice=port)
        note = (", secrets generated" if state["env_created"]
                else ", .env repaired" if state["env_repaired"] else "")
        print(f"Workspace: {state['workspace']} "
              f"(release {state['version']}{note})", file=out)

        print("Starting the stack (first run pulls the images)...", file=out)
        _compose(["up", "-d", "--remove-orphans"])
        payload = wait_healthy(log=lambda s: print(f"  {s}", file=out))
        _remember_install_id(payload)
        print(f"Engine healthy - profile={payload.get('profile')}, "
              f"install {payload.get('install_id') or 'pending'}", file=out)

    url, note = first_run_plan()
    print(f"\nFirst run: open {url}", file=out)
    print(f"  {note}", file=out)
    if open_browser:
        import webbrowser

        webbrowser.open(url)
    print("\n  status : artzain local status\n  stop   : artzain local down",
          file=out)


def run_status(manifest_src: str | None, out=None) -> None:
    out = out or sys.stdout
    pins = applied_pins()
    print(f"Workspace : {workspace_dir()}", file=out)
    print(f"Applied   : {pins.get('version') if pins else '(never installed)'}",
          file=out)
    payload = fetch_health()
    if not payload:
        print(f"Engine    : not reachable at {base_url()} — "
              "`artzain local up` starts it.", file=out)
    else:
        print(f"Engine    : {payload.get('status')} "
              f"(profile={payload.get('profile')})", file=out)
        trial = payload.get("trial") or {}
        if trial.get("applies"):
            if trial.get("expired"):
                print("Trial     : EXPIRED — new connectors/agents/keys are "
                      "paused; decisions keep sealing. Import a licence "
                      "certificate: artzain local activate <cert.json> "
                      "(it can sign you in with your dashboard email — no "
                      "API key needed).", file=out)
            else:
                print(f"Trial     : {trial.get('days_remaining')} day(s) "
                      "remaining", file=out)
        print(f"Dashboard : {base_url()}/dashboard.html", file=out)
    if pins:
        try:
            manifest = load_manifest(manifest_source(manifest_src))
            if manifest.get("version") != pins.get("version"):
                print(f"Update    : {manifest.get('version')} is available — "
                      "`artzain local upgrade`.", file=out)
            else:
                print("Update    : up to date with the stable channel.",
                      file=out)
        except LocalError:
            print("Update    : channel manifest unreachable (offline is "
                  "fine — check again later).", file=out)


def _predump(out=None) -> Path:
    """Dump the database BEFORE anything changes; refuse to proceed without.

    Binary end to end: pg_dump's bytes stream straight into the gzip file.
    A text-mode capture decoded with the locale codec (cp1252 on Windows)
    either crashed on the first emoji or silently mojibake'd the one
    artifact this function exists to protect — and buffered the whole dump
    in RAM besides.
    """
    out = out or sys.stdout
    backups_dir().mkdir(parents=True, exist_ok=True)
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    target = backups_dir() / f"pre-upgrade-{stamp}.sql.gz"
    cmd = _compose_cmd(["exec", "-T", "postgres", "pg_dump", "-U", "cognexus",
                        "-d", "cognexus"])
    written = 0
    try:
        proc = subprocess.Popen(cmd, stdout=subprocess.PIPE,
                                stderr=subprocess.PIPE)
        with gzip.open(target, "wb") as fh:
            assert proc.stdout is not None
            while True:
                chunk = proc.stdout.read(256 * 1024)
                if not chunk:
                    break
                fh.write(chunk)
                written += len(chunk)
        stderr_tail = b""
        if proc.stderr is not None:
            stderr_tail = proc.stderr.read()[-500:]
        returncode = proc.wait(timeout=1800)
    except FileNotFoundError as exc:
        raise LocalError("docker is not installed — run `artzain local "
                         "doctor` for the fix.") from exc
    except (OSError, subprocess.TimeoutExpired) as exc:
        try:
            target.unlink()
        except OSError:
            pass
        raise LocalError(f"Pre-upgrade database dump failed ({exc}) — "
                         "refusing to upgrade without one.") from exc
    if returncode != 0 or written < _MIN_DUMP_BYTES:
        try:
            target.unlink()
        except OSError:
            pass
        detail = stderr_tail.decode("utf-8", errors="replace").strip()
        raise LocalError(
            "Pre-upgrade database dump failed — refusing to upgrade without "
            "one. Is the stack running? (`artzain local up` first, then "
            f"retry.){' Details: ' + detail if detail else ''}")
    print(f"Backup: {target} ({written} bytes uncompressed)", file=out)
    return target


def run_upgrade(manifest_src: str | None, out=None) -> None:
    out = out or sys.stdout
    with _workspace_lock():
        pins = applied_pins()
        if not pins:
            raise LocalError("Nothing installed yet — run `artzain local up`.")
        manifest = load_manifest(manifest_source(manifest_src))
        if manifest.get("version") == pins.get("version"):
            print(f"Already on {pins.get('version')} — nothing to do.",
                  file=out)
            return
        print(f"Upgrading {pins.get('version')} -> {manifest.get('version')}",
              file=out)
        _predump(out=out)
        ensure_workspace(manifest)
        _compose(["up", "-d", "--remove-orphans"])
        payload = wait_healthy(log=lambda s: print(f"  {s}", file=out))
        _remember_install_id(payload)
    print(f"Upgraded — engine {payload.get('status')} on "
          f"{manifest.get('version')}. Schema migrates itself on boot; the "
          "pre-upgrade dump is in backups/ if anything looks wrong.", file=out)


def run_down(purge: bool, confirm: Callable[[str], str] = input,
             out=None) -> None:
    out = out or sys.stdout
    if not _compose_path().is_file():
        print("Nothing installed — no workspace at "
              f"{workspace_dir()}.", file=out)
        return
    with _workspace_lock():
        if not purge:
            _compose(["down"])
            print("Stopped. Data volumes kept — `artzain local up` resumes "
                  "where you left off.", file=out)
            return

        # The install id was persisted at up-time precisely so this guard
        # still names THIS install when the stack is stopped.
        pins = applied_pins() or {}
        install_id = (str(pins.get("install_id") or "").strip()
                      or str((fetch_health() or {}).get("install_id") or "").strip())
        expected = install_id or "destroy-cognexus"
        print("--purge DESTROYS the database volume AND the Ed25519 audit "
              "signing keys, which are unrecoverable (manual §2.7).", file=out)
        print("Export evidence first if you need it: artzain audit export.",
              file=out)
        typed = confirm(f"Type '{expected}' to confirm: ").strip()
        if typed != expected:
            print("Not confirmed — nothing was destroyed.", file=out)
            return
        _compose(["down", "--volumes"])
        for stale in (_compose_path(), _pins_path(), _env_path()):
            try:
                stale.unlink()
            except OSError:
                pass
        print(f"Destroyed. Backups (if any) remain in {backups_dir()}.",
              file=out)


def run_create_admin(email: str, password: str, out=None) -> None:
    out = out or sys.stdout
    token = read_env().get("COGNEXUS_BOOTSTRAP_TOKEN")
    if not token:
        raise LocalError("No bootstrap token in the workspace .env — run "
                         "`artzain local up` first.")
    status, payload = _api_post("/api/auth/bootstrap-admin", {
        "token": token, "email": email, "password": password})
    if status == 200 and payload.get("ok"):
        print(f"Platform admin created: {email}. Sign in at "
              f"{base_url()}/login", file=out)
        return
    detail = payload.get("detail")
    code = detail.get("error") if isinstance(detail, dict) else detail
    if code == "already_bootstrapped":
        raise LocalError("This install already has an account — sign in at "
                         f"{base_url()}/login instead.")
    if code == "email_exists":
        raise LocalError("An account with that email already exists — use "
                         "another email, or sign in as that account.")
    raise LocalError(f"Bootstrap failed (HTTP {status}): {code}")
